### ISSUE TITLE
Prometheus Metrics?

### ISSUE THREAD

**Issue by Henrike42** [gardener/external-dns-management#124]
Are there any prometheus metrics available at the moment?

Information about the number of dns entries would be helpful and in particular number of dns entries with status "Error".

**Comment by MartinWeindel** [comment]
It depends on what you mean with "available" prometheus metrics.
The dns-controller-manager does publish these prometheus metrics:

- `external_dns_management_account_providers`: Total number of providers per account
- `external_dns_management_dns_entries`: Total number of dns entries per hosted zone
- `external_dns_management_dns_entries_stale`: Total number of stale dns entries per hosted zone
- `external_dns_management_dns_owners`: Total number of dns entries per owner
- `external_dns_management_total_provider_requests`: Total requests per provider type and credential set

Note that the metrics name have been changed with 0.7.20, i.e. the prefix `external_dns_management_` was added.

But if you are thinking of a Gardener landscape: They are currently not available in the Prometheus of the shoot, as the dns-controller-manager is an extension, which runs on every seed only once (and not per shoot).

**Comment by MartinWeindel** [comment]
see https://github.com/gardener/gardener/issues/2946
