### ISSUE TITLE
Prometheus metrics should prefixed with the component name

### ISSUE THREAD

**Issue by mvladev** [gardener/external-dns-management#125]
**What happened**:

Prometheus metrics exposed by this component are not prefixed with the component name. See [Prometheus metrics naming best practices](https://prometheus.io/docs/practices/naming/#metric-names).

**What you expected to happen**:

Metrics should be prefixed with the component name. e.g.

`dns_entries` => `external_dns_managemeent_dns_entries`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by MartinWeindel** [comment]
Thanks for bringing this up!
