### ISSUE TITLE
Duplicate effort? (kubernetes-sigs/external-dns)

### ISSUE THREAD

**Issue by robinbraemer** [gardener/external-dns-management#127]
It seems that some parts of the project is re-implementing solutions already addressed in https://github.com/kubernetes-sigs/external-dns and so does duplicated effort. It may also be better to try to reuse dns providers from https://github.com/kubernetes-sigs/external-dns/tree/master/provider and "refactor" in some way.

I might be wrong and missed some details in why maintainers of gardener/external-dns-management decided to not do so.

**Comment by vlerenc** [comment]
Thanks for your comment @robinbraemer. We did just that 2y ago, engaged with the community, but PRs were not merged, basic requirements not accepted (cc @mandelsoft @MartinWeindel @timuthy). Please see https://github.com/gardener/external-dns-management#why-not-using-the-community-external-dns-solution why we had to solve the DNS and certificate requirement for Gardener in new components.

/discussion
/close
