### ISSUE TITLE
Finalizer convention disobeyed

### ISSUE THREAD

**Issue by rfranzke** [gardener/external-dns-management#14]
The convention for finalizers is `<domain-name>/<controller-name>`, but the dns-controller-manager uses e.g., `aws-route53/dns.gardener.cloud`. It should be `dns.gardener.cloud/aws-route53` to go with the community.

**Comment by mandelsoft** [comment]
Behaviour changed in controller manager library.
Will be picked with next update.

**Comment by MartinWeindel** [comment]
fixed with 0.2.0
