### ISSUE TITLE
DNS entry update target not work fine

### ISSUE THREAD

**Issue by zjj2wry** [gardener/external-dns-management#141]
**What happened**:
```
Name:         central
Namespace:    nightly
Labels:       app.kubernetes.io/managed-by=pulumi
Annotations:  API Version:  dns.gardener.cloud/v1alpha1
Kind:         DNSEntry
Metadata:
  Creation Timestamp:  2020-06-22T09:31:11Z
  Generation:          5
  Resource Version:    244664769
  Self Link:           /apis/dns.gardener.cloud/v1alpha1/namespaces/nightly/dnsentries/central
  UID:                 543e27b7-b57b-459b-83de-5c55caab58ba
Spec:
  Dns Name:  us-west-2.nightly.shared.EXAMPLE.com
  Targets:
    <new-target>
  Ttl:  120
Status:
  Message:              InvalidChangeBatch: [Tried to create resource record set [name='comment-us-west-2.nightly.shared.aws.EXAMPLE.com.', type='TXT'] but it already exists, Tried to create resource record set [name='us-west-2.nightly.shared.aws.EXAMPLE.com.', type='A'] but it already exists]
                        status code: 400, request id: 434c9c90-8aa8-4238-81dc-6def1ea3ef68
  Observed Generation:  2
  Provider:             nightly/external
  Provider Type:        aws-route53
  State:                Error
  Targets:
    <OLD-TARGET>
  Ttl:   120
  Zone:  -
Events:  <none>
```
I update target from an AWS nlb address to new AWS ALB address, but it will reporter InvalidChangeBatch...

**What you expected to happen**:
dns record will update successful

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by MartinWeindel** [comment]
@zjj2wry 
Please provide more details.
Which version of dns-controller-manager are you using?
Can you provide a sequence of steps how to reproduce the issue?

**Comment by zjj2wry** [comment]
> @zjj2wry
> Please provide more details.
> Which version of dns-controller-manager are you using?
> Can you provide a sequence of steps how to reproduce the issue?

thanks for the reply, I use version v2.0.1.

I use AWS route53 DNS provider, and I update the target from ELB address to ALB address.

**Comment by MartinWeindel** [comment]
@zjj2wry 
version v2.0.1 ? Such a version is not existing. Or do you mean 0.2.1??? Current version is v0.7.21.
Please check again. E.g. look for `spec.containers.image` in the pod object.

**Comment by zjj2wry** [comment]
> @zjj2wry
> version v2.0.1 ? Such a version is not existing. Or do you mean 0.2.1??? Current version is v0.7.21.
> Please check again. E.g. look for `spec.containers.image` in the pod object.

sorry, it should be `eu.gcr.io/gardener-project/dns-controller-manager:v0.7.10`

**Comment by MartinWeindel** [comment]
I cannot reproduce the problem and have also no idea what could cause it.
The logs of the dns-controller-manager would be very helpful. Can you reproduce the issue and make the relevant log lines available? (of course you can anonymise things like domain names and IP addresses).
Anyway I would recommend to update to the latest version.

**Comment by zjj2wry** [comment]
> I cannot reproduce the problem and have also no idea what could cause it.
> The logs of the dns-controller-manager would be very helpful. Can you reproduce the issue and make the relevant log lines available? (of course you can anonymise things like domain names and IP addresses).
> Anyway I would recommend to update to the latest version.

@MartinWeindel seems this DNS should be managed by another DNS class, so skip the update event...
we will bump the version and add `dns.gardener.cloud/class=garden-setup` annotation fixes it. thank you very much
```
time="2020-11-27T03:13:46Z" level=debug msg="aws-route53: default: 1: obj:default:dns.gardener.cloud/DNSEntry/nightly/central: nightly/central: annotated dns class \"gardendns\" does not match specified class set ['garden-setup'] -> skip "
time="2020-11-27T03:13:46Z" level=debug msg="aws-route53: default: 1: obj:default:dns.gardener.cloud/DNSEntry/nightly/central: removing unknown entry \"nightly/central\""
```
