### ISSUE TITLE
What are the TXT-records for?

### ISSUE THREAD

**Issue by SamDecrock** [gardener/external-dns-management#154]
Hi, when I add a new DNSEntry, it also creates 2 TXT-entries:
- one containing `"prefix=comment-"`
- one containing `"owner=myprefix"`

What are they for and can I disable this?

Sam

**Comment by SamDecrock** [comment]
Thanks, Sorry, I didn't notice I created the ticket in the wrong repo.

**Comment by MartinWeindel** [comment]
As @Diaphteiros correctly told, these TXT records are metadata needed to distinguish DNS records which are managed by one instance of dns-controller-manager from other instances or manual managed records.
see https://github.com/gardener/external-dns-management#owner-identifiers
There is no way to disable them.

**Comment by SamDecrock** [comment]
Ok, but what's the `"prefix=comment-"` for?

**Comment by MartinWeindel** [comment]
This is the prefix of the dns name to store the metadata. E.g. the domain name of the metadata TXT recordset for the domain name `a.b.c.com` is `comment-a.b.c.com`.

**Comment by SamDecrock** [comment]
Hmm, mine just says `"prefix=comment-"` : 
![Screenshot 2021-03-04 at 08 14 56](https://user-images.githubusercontent.com/550487/109925194-bc066480-7cc1-11eb-82b8-1b4ce5a3334a.png)
