### ISSUE TITLE
Align Helm and example resources with release

### ISSUE THREAD

**Issue by timuthy** [gardener/external-dns-management#21]
This repository offers a Helm Chart as well as an `ControllerRegistration` example file which are supposed to follow release cycles.

Therefore, the following fields should be updated during the release:

- `deployment.providerConfig.chart` and `deployment.providerConfig.values.image.tag` in `examples/gardener-controllerregistration.yaml`
- `image.tag` in `charts/external-dns-management/values.yaml`

Similar challenges were already tackled in [gardener/controller-extensions](https://github.com/gardener/gardener-extensions) and can serve as a reference:

- `ControllerRegistration` generation: https://github.com/gardener/gardener-extensions/blob/master/hack/generate-controller-registration.sh
- Prepare release step: https://github.com/gardener/gardener-extensions/blob/master/.ci/prepare_release

**Comment by MartinWeindel** [comment]
Implemented with release 0.4.0.

Thanks for the references, they have been very useful.
