### ISSUE TITLE
Controller calls route53 ListResourceRecordSets for each hosted zone in AWS account

### ISSUE THREAD

**Issue by amiramw** [gardener/external-dns-management#240]
**What happened**:

The DNS manager controller calls once in a while (20 minutes by current setting) to each hosted zone in the configured AWS account.
with many hosted zones and many developers this easily cause rate exceeded on route53 side (where it is allows 5 calls per seconds per account)

**What you expected to happen**:

These query should apply only to hosted zones applicable to one of the existing DNS providers unless I'm missing something.

**How to reproduce it (as minimally and precisely as possible)**:

- Create several hosted zones
- Create DNS provider for one of them
- Monitor route53 calls in cloud watch or so and see that once in 20 minutes all hosted zones are called with ListResourceRecordSets 

**Anything else we need to know**:
N/A

**Environment**:
N/A

**Comment by MartinWeindel** [comment]
This is a feature not a bug! 
The DNS controller manager has a zone state cache and resyncs it periodically with the hosted zone of the DNS provider backend. The default value is 15 min for standard deployments (30 min for SAP Gardener landscapes).

If you are using an own deployment of the dns-controller-manager, there are two ways to change time period for refreshing/synchronising it.

1. Globally change the Helm configuration value `configuration.dnsPoolResyncPeriod` (corresponds to the command-line option `dns.pool.resync-period`)
2. If you want to change the resync period for some hosted zones, create a `DNSHostedZonePolicy` resource and set the `policy.zoneStateCacheTTL` as you need ([see example here](https://github.com/gardener/external-dns-management/blob/master/examples/80-dnshostedzonepolicy.yaml))

If you are sure that there no conflicts for writing the same DNS records from different applications (dns-controller-manager or others), you can change the resync-period or zoneStateCacheTTL to 24h.

In case you are using the dns-controller-manager indirectly with DNSProviders in a SAP Gardener landscape, please contact me directly for possible adjustments and side effects.

**Comment by amiramw** [comment]
Thanks @MartinWeindel! 
What kind of problems should we expect if we define large resync period?

**Comment by MartinWeindel** [comment]
It depends on your environment.
If you are only using a single DNS controller manager and no other applications are managing DNS records in the same hosted zones, the resync is not really needed. Same if you know, that the records touched by the DNS controller manager will never be changed by anyone else.

One possible problem is recreation of DNS entries by different instances. One Example:
Let's assume there are two DNS controller manager (with different owner identifiers as requested) working on the same hosted zone `example.org`. Let's name them D1 and D2.
- D1 creates a `DNSEntry` for `foo.example.org` with target `1.2.3.4`. The DNS controller manager creates two DNS records: the `A` record and a `TXT` record with metadata containing its owner identifier.
- After a resync, D2 becomes aware of these changes.
- D1 deletes the `DNSEntry` for `foo.example.org`.
- D2 creates `DNSEntry` for `foo.example.org` before it has another resync of the zone state. This will fail as the zone state cache of D2 is outdated. It thinks the DNS record is still existing and belongs to D1. So the entry will show an error like "busy for another owner"
- After a resync, D2 becomes aware of the last changes.
- Only now D2 can create the DNS records for `foo.example.org`

**Comment by amiramw** [comment]
those problems can occur if I use more than one replica as well, right?

**Comment by MartinWeindel** [comment]
With multiple replicas only the leader keeps a zone state. If another replica becomes the leader, it will resync first. Those problems cannot occur in this case.
