### ISSUE TITLE
Release v0.12.7 incompatible with gardener version < v1.50

### ISSUE THREAD

**Issue by gesslein** [gardener/external-dns-management#269]
**What happened**:
external-dns-management v0.12.7 contains a [change](https://github.com/gardener/external-dns-management/commit/e44be838c9761684ff27da5243b817510d5ab50f) that sets the priorityClassName to gardener-system-900
This PriorityClass was only added in gardener 1.50, so with older versions will cause the extension deployment to be unable to launch a pod.

**What you expected to happen**:
external-dns-management patch releases to be always backwards compatible and an explicit breaking change noted in the release notes for a new minor version if gardener compatability has changed.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy ControllerRegistration/ControllerDeployment of v0.12.7 to gardener version < 1.50

**Comment by MartinWeindel** [comment]
@gesslein Thanks for reporting. You're right, it was missed to add it to the release notes.

**Comment by gesslein** [comment]
Thank you for adding it to the release notes! Since your versioning at least looks like semver I still find that to be a surprising breaking change in a "patch" release, but that might just be me making an assumption.

**Comment by MartinWeindel** [comment]
I have not been aware of this breaking change on releasing. Internal communication could have been better.
We will take more care in the future.
