### ISSUE TITLE
provide AWS Alias entry to reduce infra costs

### ISSUE THREAD

**Issue by freegroup** [gardener/external-dns-management#27]
Amazon Route 53 alias records provide a Route 53-specific extension to the DNS function. Alias records allow you to forward traffic to selected AWS resources, such as CloudFront distributions and Amazon S3 buckets. You can also forward traffic from one record in a hosted zone to another.

This reduces the cost of a cluster.

Right now - only entries for AWS LB are required....

<img width="1091" alt="Bildschirmfoto 2019-05-24 um 13 42 54" src="https://user-images.githubusercontent.com/1155039/58325469-240bf380-7e2a-11e9-8ea6-faf4b83f5375.png">

**Comment by MartinWeindel** [comment]
resolved with PR #28

**Comment by freegroup** [comment]
Wenn ich den Code richtig verstehe, dann schaut Ihr auf den Namen des Target und im Fall eines LB, legt ihr ein Alias an - oder? Es ist keine spezielle config notwendig.

**Comment by MartinWeindel** [comment]
Yes, no special configuration needed. All AWS ELBs are maintained in an internal list. We expect no frequent updates to this list, so an explicit configuration seems to be overkill.
