### ISSUE TITLE
azure DNS -  setting @ entry (apex) is not possible

### ISSUE THREAD

**Issue by sundbing** [gardener/external-dns-management#272]
when adding an @ entry in Azure DNS, the follwowing error shows up:
"@.our.custom.domain" is no valid dns name ([a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')])"

we need to add the apex domain to point to our web shell for the basic domain.
It is possible to add it manually in Azure DNS via portal or cli, but not via gardener.

Recap:
- create a new DNSEntry in dns.gardener.cloud/v1alpha1 and add dnsName: '@.your.custom.domain'
- save the DNSEntry and push it to kubernetes

**Comment by MartinWeindel** [comment]
Maybe we can add a flag to disable the DNS name validation.
In general, we will keep the validation even if some provider may allow names not covered by the RFCs.

**Comment by MartinWeindel** [comment]
Reopening as it is also requested in the context of shoot-dns-service, where the solution #276 is not viable.
