### ISSUE TITLE
Increase the limit on the number of targets

### ISSUE THREAD

**Issue by TomerJLevy** [gardener/external-dns-management#283]
**What would you like to be added**:
Why do we limit the number of targets to 11? (as seen [here](https://github.com/gardener/external-dns-management/blob/master/pkg/dns/provider/entry.go#L777))

**Why is this needed**:
We're experiencing it when trying to create DNS Entry with more than 11 targets

**Comment by MartinWeindel** [comment]
@TomerJLevy  We need some limit here for security reasons. What limit would you suggest?

**Comment by TomerJLevy** [comment]
Hi Martin, thanks for the feedback. Is there a reason why you chose 11? Is there any AWS/other cloud service provider limitation or guidelines that you follow?
Maybe we can make it configurable and put a low default value and also set a maximum value for that security reason you specified

**Comment by MartinWeindel** [comment]
This restriction applies only to multiple CNAME targets. That's a unique feature of the dns-controller-manager and is not directly supported by the backends. Instead it is needed to lookup each CNAME individually. Each target may itself have multiple IP addresses both IPv4 and IPv6. Therefore we need to restrict it.
There is no special reason why it is exactly 11, but I'm very surprised that it is not enough for all practical use cases.
It is no option to make it configurable, sorry.
We can discuss about doubling it, but I would like to understand how you are using this feature (if you are allowed to talk about it).

**Comment by Limorerez** [comment]
Hi Martin,
Thank you for your response. 
Is it possible to double it? 

Best regards,
Limor

**Comment by MartinWeindel** [comment]
Yes I will make a PR for that in the next days.
