### ISSUE TITLE
Unable to configure TXT records that are longer than 

### ISSUE THREAD

**Issue by Limorerez** [gardener/external-dns-management#284]
What would you like to be added:
We are currently having issues with creating TXT record with over 255 characters in Route53.
We would appreciate it if you could follow AWS guidelines for management of TXT records that are longer than 255 chars( i.e. "splitting the string into multiple 255-char strings, a TXT value of up to 4000 chars is supported. ")
Guidelines: [https://aws.amazon.com/premiumsupport/knowledge-center/route-53-configure-long-spf-txt-records/#:~:text=A%20TXT%20record%20contains%20one,TXT%20record%20is%204%2C000%20characters.”](https://aws.amazon.com/premiumsupport/knowledge-center/route-53-configure-long-spf-txt-records/#:~:text=A%20TXT%20record%20contains%20one,TXT%20record%20is%204%2C000%20characters.%E2%80%9D)

Why is this needed:
The way we generate these records it sometimes exceeds 255 chars

Best regards,
Limor

**Comment by MartinWeindel** [comment]
You have to split the text yourself in multiple strings. 
The `DNSEntry` supports a list of text fields which maps one-to-one to DNS records. If we now would split a text field, we could not restore the original layout. Therefore please just split the text yourself.

**Comment by yaelShechter** [comment]
As far as I know, the value of the TXT record is created in [your code](https://github.com/gardener/external-dns-management/blob/59f5745a723ea70b221c1ef2ff16e461a8b5c490/pkg/dns/provider/changemodel.go#L552), so we don't have the ability to split the text.

**Comment by MartinWeindel** [comment]
@yaelShechter Thanks for clarifying! You are talking about the meta data TXT record generated for each `DNSEntry`, not about own created `DNSEntry` with type TXT.

**Comment by MartinWeindel** [comment]
This is related to #283 with many CNAME targets.

**Comment by MartinWeindel** [comment]
obsolete
