### ISSUE TITLE
Option for creating DNSEntry without ingress annotation

### ISSUE THREAD

**Issue by cihangirbesiktas** [gardener/external-dns-management#31]
Currently, it is required to add an annotation into ingress definition. The annotation also requires the host which is already in the spec. This is duplication and error-prone.

Is it possible to add an option so that the DNSEntry will be created without an annotation?

**Comment by MartinWeindel** [comment]
This feature is already implemented, but not documented.

You have to add the annotation:
```yaml
annotations:
  dns.gardener.cloud/dnsnames: all
```
