### ISSUE TITLE
Cloudflare secret docs incorrectly use base64-encoded token

### ISSUE THREAD

**Issue by SeanKilleen** [gardener/external-dns-management#360]
**What happened**: 

I set up a DNS provider using [the steps for the Cloudflare token](https://github.com/gardener/external-dns-management/blob/master/docs/cloudflare/README.md) within SAP BTP Kyma.

I saw an error within Kyma for the DNS Provider:

![314167796-52580609-2f05-4e23-8e47-dd344b620de4](https://github.com/gardener/external-dns-management/assets/2148318/eef7fbce-174c-4933-b0d6-d4d528528096)

**What you expected to happen**:

I expected the process to work, which it did, once I removed the base64 encoding from the secret.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the external DNS management setup for Cloudflare.

**Anything else we need to know**: I'll submit a PR for this.

**Environment**:

**Comment by SeanKilleen** [comment]
Realizing that this issue may have been because I was submitting the k8s secret via Terraform, which may automatically base64 encode the value. If that's the case, this issue and my PR can both be closed.

**Comment by MartinWeindel** [comment]
The documentation is correct, but it can be cause confusion, as the base64 encoding is more details about how to create a Kubernetes secret. I adjusted your PR to make it correct and clearer. Thank you for the feedback!
