### ISSUE TITLE
non unique version mapping for VirtualService.networking.istio.io

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/external-dns-management#368]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
The extension does not support istio CRD from version `networking.istio.io/v1`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with shoot-dns-service extension enabled.

2. Create istio CRDs from https://raw.githubusercontent.com/istio/istio/master/manifests/charts/base/crds/crd-all.gen.yaml.

3. Make sure shoot-dns-service Pod in the Shoot control plane fails with:
```
$ k logs shoot-dns-service-5f88589ddd-l5pz5

creating reconciler default failed: gardener/cml/resources/NON_UNIQUE_MAPPING: non unique version mapping for VirtualService.networking.istio.io
```

```
$ k api-resources | grep virtualservices
virtualservices                    vs                  networking.istio.io/v1                 true         VirtualService
```

**Anything else we need to know?**:

**Environment**:

- External-dns-management version: v0.18.5

**Comment by AleksandarSavchev** [comment]
cc @MartinWeindel

**Comment by MartinWeindel** [comment]
Thanks for reporting the new version.
