### ISSUE TITLE
DNSEntry creation failed  .spec.resolveTargetsToAddresses: field not declared in schema

### ISSUE THREAD

**Issue by saifulhoque26** [gardener/external-dns-management#389]
**What happened**:
Error from server: failed to create typed patch object (haproxy-ingress/haproxy-nlb-service; dns.gardener.cloud/v1alpha1, Kind=DNSEntry): .spec.resolveTargetsToAddresses: field not declared in schema 

**What you expected to happen**:
Gardener accepted our feature request: https://github.com/gardener/external-dns-management/issues/371 

The PR with the feature is merged: 
https://github.com/gardener/external-dns-management/pull/377

As per the [documentation](https://github.com/gardener/external-dns-management/pull/377/files#diff-64279a46563f8fd55de369c948ec575e69249e2a7a6c7fb139410358c9abb90cR159), we can create an A record with a single target

The version [gardener-extension-shoot-dns-service](https://github.com/gardener/gardener-extension-shoot-dns-service) [v1.49.0](https://github.com/gardener/gardener-extension-shoot-dns-service/releases/tag/v1.49.0) contains the fix. 

--deleted internal references--

```
Error from server: failed to create typed patch object (haproxy-ingress/haproxy-nlb-service; dns.gardener.cloud/v1alpha1, Kind=DNSEntry): .spec.resolveTargetsToAddresses: field not declared in schema 
```

**How to reproduce it (as minimally and precisely as possible)**:
Now:

--deleted internal references--

**Anything else we need to know**:

**Environment**:

**Comment by MartinWeindel** [comment]
Cannot reproduce the issue. Looking on the demo-gcp-dmi shoot cluster it looks as if the CRD was overwritten with `kubectl apply`, as the following output suggests:

```bash
# on the demo-gcp-dmi shoot
$ k get crd dnsentries.dns.gardener.cloud -oyaml --show-managed-fields
...
   - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:hc.sap.com/hc-provisioned: {}
      f:spec:
        f:conversion:
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:scope: {}
    manager: kubectl
    operation: Apply
    time: "2024-08-30T11:32:53Z"
...
```

**Comment by MartinWeindel** [comment]
> @saifulhoque26 You have mentioned internal references in the public. Please check.

I have removed the internal references.
