### ISSUE TITLE
DNS resolve timeout

### ISSUE THREAD

**Issue by syhan** [gardener/external-dns-management#55]
Dear colleagues,

We've deployed v0.7.6 to our gardener cluster which hosted on alibaba cloud, after the dns controller manager got deployed, we still could not do any name resolve,  by observing coredns log, it continuously produce error log like
```
[ERROR] plugin/errors: 2 izbp1ggudxumgfip9jsn60z. AAAA: read udp 100.96.0.17:55171->100.100.2.136:53: i/o timeout
[INFO] 100.96.0.16:35403 - 49792 "A IN checkip.amazonaws.com. udp 39 false 512" NOERROR - 0 2.000216725s
[ERROR] plugin/errors: 2 checkip.amazonaws.com. A: read udp 100.96.0.17:52579->100.100.2.136:53: i/o timeout
[INFO] 100.96.0.21:38277 - 6361 "AAAA IN alidns.aliyuncs.com. udp 37 false 512" NOERROR - 0 2.000200547s
[ERROR] plugin/errors: 2 alidns.aliyuncs.com. AAAA: read udp 100.96.0.17:32784->100.100.2.136:53: i/o timeout
```  

the DNS provider we use
```
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: alicloud-dns-provider
  namespace: default
spec:
  type: alicloud-dns
  secretRef:
    name: alicloud-dns-credentials
  domains:
    include:
    - shoot.can.k8s.vlab-sapcloudplatformdev.cn

```

Thanks

**Comment by jia-jerry** [comment]
It seems the Alpine 3.10 can't handle SERVFAIL from DNS server gracefully. I found v3.11 has no such issue.

**Comment by MartinWeindel** [comment]
@syhan I'm not sure, if I understood why you created an issue here.

The DNS controller manager is responsible for managing DNS entries, but it is no DNS server. It has nothing to do with the operational lookup of DNS names, it only creates the DNS records via an api at the DNS server backend.
The log above seems to come from CoreDNS trying to reach two DNS servers. The i/o timeout is a network problem, maybe some firewall blocking UDP or some Kubernetes network policy issue.

**Comment by syhan** [comment]
@MartinWeindel Thanks for clarifying this, after doing some troubleshooting with our colleagues, it might be some conflict with the default network setting between gardener and alibaba cloud, here's another issue created https://github.com/gardener/gardener/issues/1963

**Comment by MartinWeindel** [comment]
network problem
