### ISSUE TITLE
Add Cloudflare as a DNS provider

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [gardener/external-dns-management#58]
**What would you like to be added**:
I would like to see Cloudflare as a DNS provider
**Why is this needed**:
Cloudflare is one of the biggest names in the internet and is one of the largest DNS providers. We ourselves are using Cloudflare as our DNS provider and the [cert-manager](https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/) project itself has Cloudflare as a supported provider for ACME deployments.

**Comment by MartinWeindel** [comment]
@SayakMukhopadhyay Any contributions are highly welcome. Take a look at https://github.com/gardener/external-dns-management#how-to-implement-provisioning-controllers to get started. If you need any help, just ask.
