### ISSUE TITLE
Make external-dns-management DNS provider abstraction bin?

### ISSUE THREAD

**Issue by smtalk** [gardener/external-dns-management#62]
**What would you like to be added**:
external-dns-management seems to be kubernetes-specific now (please correct me if I'm wrong). I'd be nice to make it a CLI utility which would be like an abstraction layer for DNS providers. That way people could use it to get all the DNS records for the specified zone/add any record there too. I was unable to find any utility like this, and we're thinking if we should code a totally new one, or.. just suggest a project like external-dns-management to become usable for such use-cases too.

**Why is this needed**:
external-dns-management already has a list of DNS providers supported, so, it might be not so hard to adapt it for other use-cases and attract more customers/developers to participate in the project.

Just an idea though.

**Comment by MartinWeindel** [comment]
Thanks for the interesting idea.
As you said, this project is only used within Kubernetes clusters. It has even a focus on working on multiple clusters. It uses a lot of the K8s code infrastructure, uses K8s to store state, and as a part of the Gardener project ("fully-managed, 100% certified Kubernetes clusters for homogeneous operations on any cloud and at massive scale") this is and will be the focus.
But as this project is open source, feel free to use parts of it as a starting point or as a library.

**Comment by MartinWeindel** [comment]
closed as stale
