### ISSUE TITLE
dnsannotations.dns.gardener.cloud

### ISSUE THREAD

**Issue by rushins** [gardener/external-dns-management#96]
Hi There

We are trying to install on rancher kubernetes cluster in one of the SAP internal datacenter cluster and getting this error. 

    Error: CustomResourceDefinition.apiextensions.k8s.io "dnsannotations.dns.gardener.cloud" is invalid: metadata.name: Invalid value: "dnsannotations.dns.gardener.cloud": must be spec.names.plural+"."+spec.group

Can someone help on this .

BR
Rushi.

**Comment by vlerenc** [comment]
You have not provided any information, what you did, what cluster you are using (Rancher is not sufficiently specific and then of course there is the K8s version). Since this component exists since years and is deployed thousands of times, I don't think this is a general problem.

**Comment by MartinWeindel** [comment]
The helm charts are not used by Gardener and we missed to check the last changes.

**Comment by MartinWeindel** [comment]
Thanks for reporting this issue. Now fixed on master and with release v0.7.13

**Comment by rushins** [comment]
thank you, Martin. how do i download this specific version becuase i only did the GIT clone

**Comment by MartinWeindel** [comment]
If you have cloned before the release, do a `git pull`.
Then `git checkout v0.7.13`
